# Site settings
title: Fabien Joly - Haute fleuristerie
email: contact@fabien-joly.com
description: FJ site description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://fabien-joly.com"

collections:
  project:
    output: true

# Build settings
markdown: kramdown

plugins:
  - jekyll-multiple-languages-plugin

languages: ["fr", "en"]
exclude_from_localizations: ["assets"]
